modLoader="kotlinforforge" #mandatory
loaderVersion="[3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MPL2.0"
issueTrackerURL="https://github.com/Xwaffle1/CobblemonExtras/issues"

[[mods]] #mandatory
modId="cobblemonaddonskeleton" #mandatory
version="${version}" #mandatory
displayName="Cobblemon Addon Skeleton" #mandatory
displayURL="https://amo.coffee"
#logoFile="examplemod.png" #optional
credits="Thanks to the Cobblemon Community."
authors="Cobblemon Addon Skeleton"
description='''
This is an example mod for the Cobblemon Addon Skeleton.
'''

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

[[dependencies.cobblemonaddonskeleton]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"

[[dependencies.cobblemonaddonskeleton]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[40,)" #mandatory

[[dependencies.cobblemonaddonskeleton]]
modId="architectury"
mandatory=true
versionRange="[6.5.69,)"